import re
import matplotlib.pyplot as plt

# Mostly generated by GPT-4

input_string = """
INFO:root:Experiment running on device: cuda:0
INFO:root:Learning rate: 0.25
INFO:root:number of clients: 2, len trial user name: 2
communication round: 0
INFO:root:Start to work on communication round-0
INFO:root:*****************************************************************************************
INFO:root:| Matched model on Global Testset | valid loss 2115.40 | pred: 152/4794 | acc: 3.1706%
INFO:root:*****************************************************************************************
layer: 0
max_layer 1
permuted nodes  0
permuted nodes  0
permuted nodes  0
test data size: 23587
Epoch: 0
total_loss:  1294.5205924510956
test data size: 19548
Epoch: 0
total_loss:  1088.6153211593628
INFO:root:| Matched model on Global Testset | valid loss 2115.40 | pred: 152/4794 | acc: 3.1706%
layer: 1
max_layer 1
permuted nodes  0
permuted nodes  0
permuted nodes  0
test data size: 23587
Epoch: 0
total_loss:  1229.7703318595886
test data size: 19548
Epoch: 0
total_loss:  1032.047621011734
INFO:root:| Matched model on Global Testset | valid loss 2115.40 | pred: 152/4794 | acc: 3.1706%
layer: 2
max_layer 1
permuted nodes  0
permuted nodes  0
permuted nodes  2
test data size: 23587
Epoch: 0
total_loss:  1213.2652492523193
test data size: 19548
Epoch: 0
total_loss:  1017.6698489189148
INFO:root:| Matched model on Global Testset | valid loss 2115.40 | pred: 152/4794 | acc: 3.1706%
layer: 3
max_layer 1
permuted nodes  0
permuted nodes  0
permuted nodes  2
test data size: 23587
Epoch: 0
total_loss:  1204.8814902305603
test data size: 19548
Epoch: 0
total_loss:  1010.7388880252838
INFO:root:| Matched model on Global Testset | valid loss 2115.40 | pred: 152/4794 | acc: 3.1706%
layer: 4
max_layer 1
permuted nodes  0
permuted nodes  0
permuted nodes  0
test data size: 23587
Epoch: 0
total_loss:  1201.4799194335938
test data size: 19548
Epoch: 0
total_loss:  1006.1272342205048
INFO:root:| Matched model on Global Testset | valid loss 2115.40 | pred: 152/4794 | acc: 3.1706%
layer: 5
max_layer 1
permuted nodes  0
permuted nodes  0
permuted nodes  0
test data size: 23587
Epoch: 0
total_loss:  1197.1655297279358
test data size: 19548
Epoch: 0
total_loss:  1003.1419439315796
INFO:root:| Matched model on Global Testset | valid loss 2115.40 | pred: 152/4794 | acc: 3.1706%
INFO:root:*****************************************************************************************
INFO:root:| Matched model on Global Testset | valid loss 1222.11 | pred: 1328/4794 | acc: 27.7013%
INFO:root:*****************************************************************************************
communication round: 1
INFO:root:Start to work on communication round-1
INFO:root:*****************************************************************************************
INFO:root:| Matched model on Global Testset | valid loss 1222.11 | pred: 1328/4794 | acc: 27.7013%
INFO:root:*****************************************************************************************
layer: 0
max_layer 1
permuted nodes  0
permuted nodes  0
permuted nodes  0
test data size: 23587
Epoch: 0
total_loss:  1200.8548331260681
test data size: 19548
Epoch: 0
total_loss:  1003.330600976944
INFO:root:| Matched model on Global Testset | valid loss 1222.11 | pred: 1328/4794 | acc: 27.7013%
layer: 1
max_layer 1
permuted nodes  0
permuted nodes  0
permuted nodes  0
test data size: 23587
Epoch: 0
total_loss:  1195.5912346839905
test data size: 19548
Epoch: 0
total_loss:  1000.999858379364
INFO:root:| Matched model on Global Testset | valid loss 1222.11 | pred: 1328/4794 | acc: 27.7013%
layer: 2
max_layer 1
permuted nodes  0
permuted nodes  0
permuted nodes  0
test data size: 23587
Epoch: 0
total_loss:  1192.9717705249786
test data size: 19548
Epoch: 0
total_loss:  996.9786565303802
INFO:root:| Matched model on Global Testset | valid loss 1222.11 | pred: 1328/4794 | acc: 27.7013%
layer: 3
max_layer 1
permuted nodes  0
permuted nodes  0
permuted nodes  0
test data size: 23587
Epoch: 0
total_loss:  1191.3083319664001
test data size: 19548
Epoch: 0
total_loss:  995.4054815769196
INFO:root:| Matched model on Global Testset | valid loss 1222.11 | pred: 1328/4794 | acc: 27.7013%
layer: 4
max_layer 1
permuted nodes  0
permuted nodes  0
permuted nodes  0
test data size: 23587
Epoch: 0
total_loss:  1189.491417646408
test data size: 19548
Epoch: 0
total_loss:  993.864572763443
INFO:root:| Matched model on Global Testset | valid loss 1222.11 | pred: 1328/4794 | acc: 27.7013%
layer: 5
max_layer 1
permuted nodes  0
permuted nodes  0
permuted nodes  0
test data size: 23587
Epoch: 0
total_loss:  1186.3376960754395
test data size: 19548
Epoch: 0
total_loss:  992.2258434295654
INFO:root:| Matched model on Global Testset | valid loss 1222.11 | pred: 1328/4794 | acc: 27.7013%
INFO:root:*****************************************************************************************
INFO:root:| Matched model on Global Testset | valid loss 1196.11 | pred: 1355/4794 | acc: 28.2645%
INFO:root:*****************************************************************************************
communication round: 2
INFO:root:Start to work on communication round-2
INFO:root:*****************************************************************************************
INFO:root:| Matched model on Global Testset | valid loss 1196.11 | pred: 1355/4794 | acc: 28.2645%
INFO:root:*****************************************************************************************
layer: 0
max_layer 1
permuted nodes  0
permuted nodes  0
permuted nodes  0
test data size: 23587
Epoch: 0
total_loss:  1190.4257361888885
test data size: 19548
Epoch: 0
total_loss:  992.7968657016754
INFO:root:| Matched model on Global Testset | valid loss 1196.11 | pred: 1355/4794 | acc: 28.2645%
layer: 1
max_layer 1
permuted nodes  0
permuted nodes  0
permuted nodes  0
test data size: 23587
Epoch: 0
total_loss:  1189.1297297477722
test data size: 19548
Epoch: 0
total_loss:  991.9495003223419
INFO:root:| Matched model on Global Testset | valid loss 1196.11 | pred: 1355/4794 | acc: 28.2645%
layer: 2
max_layer 1
permuted nodes  0
permuted nodes  0
permuted nodes  0
test data size: 23587
Epoch: 0
total_loss:  1185.4400827884674
test data size: 19548
Epoch: 0
total_loss:  991.5523257255554
INFO:root:| Matched model on Global Testset | valid loss 1196.11 | pred: 1355/4794 | acc: 28.2645%
layer: 3
max_layer 1
permuted nodes  0
permuted nodes  0
permuted nodes  0
test data size: 23587
Epoch: 0
total_loss:  1184.214814901352
test data size: 19548
Epoch: 0
total_loss:  989.3693981170654
INFO:root:| Matched model on Global Testset | valid loss 1196.11 | pred: 1355/4794 | acc: 28.2645%
layer: 4
max_layer 1
permuted nodes  0
permuted nodes  0
permuted nodes  0
test data size: 23587
Epoch: 0
total_loss:  1185.2385714054108
test data size: 19548
Epoch: 0
total_loss:  988.8145732879639
INFO:root:| Matched model on Global Testset | valid loss 1196.11 | pred: 1355/4794 | acc: 28.2645%
layer: 5
max_layer 1
permuted nodes  0
permuted nodes  0
permuted nodes  0
test data size: 23587
Epoch: 0
total_loss:  1182.3631799221039
test data size: 19548
Epoch: 0
total_loss:  989.4444954395294
INFO:root:| Matched model on Global Testset | valid loss 1196.11 | pred: 1355/4794 | acc: 28.2645%
INFO:root:*****************************************************************************************
INFO:root:| Matched model on Global Testset | valid loss 1196.75 | pred: 1352/4794 | acc: 28.2019%
INFO:root:*****************************************************************************************
communication round: 3
INFO:root:Start to work on communication round-3
INFO:root:*****************************************************************************************
INFO:root:| Matched model on Global Testset | valid loss 1196.75 | pred: 1352/4794 | acc: 28.2019%
INFO:root:*****************************************************************************************
layer: 0
max_layer 1
permuted nodes  0
permuted nodes  0
permuted nodes  0
test data size: 23587
Epoch: 0
total_loss:  1184.5521821975708
test data size: 19548
Epoch: 0
total_loss:  988.2420718669891
INFO:root:| Matched model on Global Testset | valid loss 1196.75 | pred: 1352/4794 | acc: 28.2019%
layer: 1
max_layer 1
permuted nodes  0
permuted nodes  0
permuted nodes  0
test data size: 23587
Epoch: 0
total_loss:  1184.749251127243
test data size: 19548
Epoch: 0
total_loss:  987.7316904067993
INFO:root:| Matched model on Global Testset | valid loss 1196.75 | pred: 1352/4794 | acc: 28.2019%
layer: 2
max_layer 1
permuted nodes  0
permuted nodes  0
permuted nodes  0
test data size: 23587
Epoch: 0
total_loss:  1184.2858128547668
test data size: 19548
Epoch: 0
total_loss:  988.8021342754364
INFO:root:| Matched model on Global Testset | valid loss 1196.75 | pred: 1352/4794 | acc: 28.2019%
layer: 3
max_layer 1
permuted nodes  0
permuted nodes  0
permuted nodes  0
test data size: 23587
Epoch: 0
total_loss:  1183.0450580120087
test data size: 19548
Epoch: 0
total_loss:  989.0750460624695
INFO:root:| Matched model on Global Testset | valid loss 1196.75 | pred: 1352/4794 | acc: 28.2019%
layer: 4
max_layer 1
permuted nodes  0
permuted nodes  0
permuted nodes  0
test data size: 23587
Epoch: 0
total_loss:  1182.5361866950989
test data size: 19548
Epoch: 0
total_loss:  986.7954158782959
INFO:root:| Matched model on Global Testset | valid loss 1196.75 | pred: 1352/4794 | acc: 28.2019%
layer: 5
max_layer 1
permuted nodes  0
permuted nodes  0
permuted nodes  0
test data size: 23587
Epoch: 0
total_loss:  1180.1564583778381
test data size: 19548
Epoch: 0
total_loss:  989.2929956912994
INFO:root:| Matched model on Global Testset | valid loss 1196.75 | pred: 1352/4794 | acc: 28.2019%
INFO:root:*****************************************************************************************
INFO:root:| Matched model on Global Testset | valid loss 1204.37 | pred: 1350/4794 | acc: 28.1602%
INFO:root:*****************************************************************************************
"""

def extract_accuracies(input_string):
    accuracies = []
    lines = input_string.split("\n")
    for i, line in enumerate(lines):
        if "acc:" in line:
            if i == 0 or i == len(lines) - 1:
                continue
            if "*****" not in lines[i - 1] and "*****" not in lines[i + 1]:
                accuracy = float(re.search("acc: ([0-9.]+)%", line).group(1))
                accuracies.append(accuracy)
    return accuracies


def plot_accuracies(accuracies):
    plt.plot(accuracies)
    plt.xlabel("Iterations")
    plt.xticks([0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
    plt.vlines([4.5, 9.5, 14.5], 0, 100, linestyles="dashed")
    plt.ylim(0, 35)
    plt.ylabel("Accuracy (%)")
    name = "FedMA"
    plt.title(name)
    plt.savefig(name + ".png")


accuracies = extract_accuracies(input_string)
plot_accuracies(accuracies)